name = "clara-code"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[env.production]
name = "clara-code"

[env.preview]
name = "clara-code-preview"
