import type { PlanTier } from "@/services/plan-limits";

export type TalentCategory = "free" | "professional" | "specialty" | "premium" | "third_party";
export type PricingModel = "free" | "one_time" | "monthly";

export interface TalentDef {
	id: string;
	displayName: string;
	description: string;
	category: TalentCategory;
	domain: string;
	industryVertical: string | null;
	pricingModel: PricingModel;
	priceUsd: number;
	monthlyPriceUsd: number | null;
	associatedGears: string[];
}

/**
 * Per-tier max Talents attached to one harness `user_agent`. Enterprise = null (contract).
 * Free tier: compact exploration cap.
 */
export const TALENTS_PER_AGENT_BY_TIER: Record<PlanTier, number | null> = {
	free: 3,
	basic: 5,
	pro: 7,
	max: 10,
	business: 15,
	enterprise: null,
};

export const FREE_TALENTS: TalentDef[] = [
	{
		id: "personal-assistant",
		displayName: "Personal Assistant",
		description: "General-purpose personal helper: calendar, email triage, note-taking",
		category: "free",
		domain: "personal",
		industryVertical: null,
		pricingModel: "free",
		priceUsd: 0,
		monthlyPriceUsd: null,
		associatedGears: ["calendar", "email", "notes"],
	},
	{
		id: "scheduling",
		displayName: "Scheduling",
		description: "Calendar management, meeting coordination, reminder logic",
		category: "free",
		domain: "personal",
		industryVertical: null,
		pricingModel: "free",
		priceUsd: 0,
		monthlyPriceUsd: null,
		associatedGears: ["calendar"],
	},
	{
		id: "email-triage",
		displayName: "Email Triage",
		description: "Read inbox, prioritize, draft replies",
		category: "free",
		domain: "personal",
		industryVertical: null,
		pricingModel: "free",
		priceUsd: 0,
		monthlyPriceUsd: null,
		associatedGears: ["email-personal"],
	},
	{
		id: "note-taking",
		displayName: "Note Taking",
		description: "Capture, organize, and link notes to tasks",
		category: "free",
		domain: "personal",
		industryVertical: null,
		pricingModel: "free",
		priceUsd: 0,
		monthlyPriceUsd: null,
		associatedGears: ["notes"],
	},
	{
		id: "summarization",
		displayName: "Summarization",
		description: "Condense long content into key points",
		category: "free",
		domain: "personal",
		industryVertical: null,
		pricingModel: "free",
		priceUsd: 0,
		monthlyPriceUsd: null,
		associatedGears: [],
	},
	{
		id: "research",
		displayName: "Research",
		description: "Web research, source verification, structured findings",
		category: "free",
		domain: "personal",
		industryVertical: null,
		pricingModel: "free",
		priceUsd: 0,
		monthlyPriceUsd: null,
		associatedGears: ["web-search", "web-fetch"],
	},
];

export const PROFESSIONAL_TALENTS: TalentDef[] = [
	{
		id: "react",
		displayName: "React Development",
		description: "Component architecture, hooks, state, modern React patterns",
		category: "professional",
		domain: "frontend",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["github", "playwright"],
	},
	{
		id: "nextjs",
		displayName: "Next.js (App Router)",
		description: "Server components, ISR, middleware, App Router patterns",
		category: "professional",
		domain: "frontend",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["github", "vercel"],
	},
	{
		id: "tailwind",
		displayName: "Tailwind CSS",
		description: "Utility-first CSS, design system implementation, responsive layout",
		category: "professional",
		domain: "frontend",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: [],
	},
	{
		id: "stripe-payments",
		displayName: "Stripe Payments",
		description: "Checkout, Connect, subscriptions, webhooks, refunds",
		category: "professional",
		domain: "backend",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["stripe"],
	},
	{
		id: "quickbooks-bookkeeping",
		displayName: "QuickBooks Bookkeeping",
		description: "Reconciliation, invoicing, A/R, financial statements",
		category: "professional",
		domain: "business",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["quickbooks"],
	},
	{
		id: "contract-drafting",
		displayName: "Contract Drafting (General)",
		description: "NDAs, service agreements, TOS, privacy policy drafts (not legal advice)",
		category: "professional",
		domain: "business",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["docusign"],
	},
	{
		id: "typescript",
		displayName: "TypeScript",
		description: "Strict types, project references, ESM, DX tooling",
		category: "professional",
		domain: "frontend",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["github"],
	},
	{
		id: "graphql-apollo",
		displayName: "GraphQL + Apollo",
		description: "Schema, resolvers, DataLoader, Apollo Server/Client",
		category: "professional",
		domain: "backend",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["github"],
	},
	{
		id: "express",
		displayName: "Express APIs",
		description: "Node HTTP APIs, middleware, validation, error handling",
		category: "professional",
		domain: "backend",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["github"],
	},
	{
		id: "postgresql",
		displayName: "PostgreSQL",
		description: "Migrations, indexing, query design, performance",
		category: "professional",
		domain: "backend",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["database"],
	},
	{
		id: "docker",
		displayName: "Docker & Containers",
		description: "Dockerfile, multi-stage images, local compose, registry",
		category: "professional",
		domain: "devops",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["docker"],
	},
	{
		id: "kubernetes",
		displayName: "Kubernetes Basics",
		description: "Deploy manifests, services, health checks, rollouts",
		category: "professional",
		domain: "devops",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["k8s"],
	},
	{
		id: "aws",
		displayName: "AWS Cloud",
		description: "IAM, S3, Lambda, App Runner, operational patterns",
		category: "professional",
		domain: "devops",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["aws"],
	},
	{
		id: "vercel",
		displayName: "Vercel Deploys",
		description: "Previews, env vars, serverless, edge",
		category: "professional",
		domain: "devops",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["vercel"],
	},
	{
		id: "redis",
		displayName: "Redis Caching",
		description: "Caching patterns, queues, rate limiting, sessions",
		category: "professional",
		domain: "backend",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["redis"],
	},
	{
		id: "playwright-qa",
		displayName: "Playwright E2E",
		description: "E2E tests, fixtures, trace viewer, CI integration",
		category: "professional",
		domain: "qa",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["playwright"],
	},
	{
		id: "clerk-auth",
		displayName: "Clerk Authentication",
		description: "Clerk, JWT, RBAC, sign-in flows, webhooks (patterns)",
		category: "professional",
		domain: "backend",
		industryVertical: null,
		pricingModel: "one_time",
		priceUsd: 4.99,
		monthlyPriceUsd: null,
		associatedGears: ["clerk"],
	},
];

export const SPECIALTY_TALENTS: TalentDef[] = [
	{
		id: "barbershop-operations",
		displayName: "Barbershop Operations",
		description: "Booking flows, walk-in handling, deposits, stylist scheduling",
		category: "specialty",
		domain: "industry",
		industryVertical: "barbershop",
		pricingModel: "one_time",
		priceUsd: 14.99,
		monthlyPriceUsd: null,
		associatedGears: ["calendar", "stripe"],
	},
	{
		id: "real-estate-transactions",
		displayName: "Real Estate Transactions",
		description: "Listings, showings, lead nurture, MLS data patterns (non-legal)",
		category: "specialty",
		domain: "industry",
		industryVertical: "real-estate",
		pricingModel: "one_time",
		priceUsd: 19.99,
		monthlyPriceUsd: null,
		associatedGears: ["mls-search", "calendar"],
	},
	{
		id: "rental-property-management",
		displayName: "Rental Property Management",
		description: "Booking, deposits, payouts, guest communications",
		category: "specialty",
		domain: "industry",
		industryVertical: "rental",
		pricingModel: "one_time",
		priceUsd: 19.99,
		monthlyPriceUsd: null,
		associatedGears: ["stripe-connect", "calendar"],
	},
	{
		id: "restaurant-pos",
		displayName: "Restaurant POS",
		description: "Orders, tables, tips, inventory (patterns)",
		category: "specialty",
		domain: "industry",
		industryVertical: "restaurant",
		pricingModel: "one_time",
		priceUsd: 24.99,
		monthlyPriceUsd: null,
		associatedGears: ["stripe", "inventory"],
	},
	{
		id: "salon-operations",
		displayName: "Salon & Spa",
		description: "Appointments, color services, rebooking, retail adds",
		category: "specialty",
		domain: "industry",
		industryVertical: "salon",
		pricingModel: "one_time",
		priceUsd: 14.99,
		monthlyPriceUsd: null,
		associatedGears: ["calendar", "stripe"],
	},
	{
		id: "fitness-gym",
		displayName: "Gym & Fitness",
		description: "Membership, class packs, trainer sessions",
		category: "specialty",
		domain: "industry",
		industryVertical: "fitness",
		pricingModel: "one_time",
		priceUsd: 12.99,
		monthlyPriceUsd: null,
		associatedGears: ["calendar", "stripe"],
	},
	{
		id: "dental-practice",
		displayName: "Dental Practice",
		description: "Appointments, treatment plans, insurance prep (non-clinical advice)",
		category: "specialty",
		domain: "industry",
		industryVertical: "dental",
		pricingModel: "one_time",
		priceUsd: 17.99,
		monthlyPriceUsd: null,
		associatedGears: ["calendar", "stripe"],
	},
	{
		id: "legal-client-intake",
		displayName: "Legal Client Intake (non-legal advice)",
		description: "Intake questions, document requests, case triage (drafting only, not legal advice)",
		category: "specialty",
		domain: "industry",
		industryVertical: "legal",
		pricingModel: "one_time",
		priceUsd: 19.99,
		monthlyPriceUsd: null,
		associatedGears: ["docusign", "email"],
	},
	{
		id: "home-services-ops",
		displayName: "Home Services (HVAC/Plumber)",
		description: "Dispatch windows, job costing, follow-ups, estimates",
		category: "specialty",
		domain: "industry",
		industryVertical: "home-services",
		pricingModel: "one_time",
		priceUsd: 15.99,
		monthlyPriceUsd: null,
		associatedGears: ["calendar", "stripe"],
	},
	{
		id: "photography-business",
		displayName: "Photography Business",
		description: "Galleries, deposits, shoot scheduling, print upsells",
		category: "specialty",
		domain: "industry",
		industryVertical: "photography",
		pricingModel: "one_time",
		priceUsd: 12.99,
		monthlyPriceUsd: null,
		associatedGears: ["calendar", "stripe"],
	},
	{
		id: "e-commerce-ops",
		displayName: "E-commerce Operations",
		description: "Catalog, promos, fulfillment, returns patterns",
		category: "specialty",
		domain: "industry",
		industryVertical: "e-commerce",
		pricingModel: "one_time",
		priceUsd: 18.99,
		monthlyPriceUsd: null,
		associatedGears: ["stripe", "inventory"],
	},
];

export const PREMIUM_TALENTS: TalentDef[] = [
	{
		id: "cpa-tax-prep",
		displayName: "CPA Tax Preparation (patterns only)",
		description: "Form prep patterns, references — not tax advice. Monthly updates for code changes",
		category: "premium",
		domain: "business",
		industryVertical: null,
		pricingModel: "monthly",
		priceUsd: 0,
		monthlyPriceUsd: 14.99,
		associatedGears: ["tax-tables", "irs-forms"],
	},
	{
		id: "attorney-ip-law",
		displayName: "IP Law Practice (advisory only)",
		description: "Trademark, copyright, application drafts. NOT legal advice",
		category: "premium",
		domain: "business",
		industryVertical: null,
		pricingModel: "monthly",
		priceUsd: 0,
		monthlyPriceUsd: 24.99,
		associatedGears: ["uspto-search"],
	},
];

export const ALL_CURATED_TALENTS: TalentDef[] = [
	...FREE_TALENTS,
	...PROFESSIONAL_TALENTS,
	...SPECIALTY_TALENTS,
	...PREMIUM_TALENTS,
];
